import { prisma } from "@/lib/db";
import { getSession } from "@/lib/auth";

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await getSession();
  if (!session?.user) return new Response("Unauthorized", { status: 401 });

  const member = await prisma.organizationMember.findFirst({ where: { userId: session.user.id } });
  if (!member) return new Response("Unauthorized", { status: 401 });

  const assessment = await prisma.assessment.findUnique({
    where: { id },
    include: {
      organization: true,
      controlResults: {
        include: {
          control: { include: { domain: { include: { framework: true } } } },
          evidence: true,
          updatedBy: { include: { user: true } },
        },
        orderBy: { control: { domain: { sortOrder: "asc" } } },
      },
    },
  });

  if (!assessment || assessment.organizationId !== member.organizationId) {
    return new Response("Not found", { status: 404 });
  }

  const total = assessment.controlResults.length;
  const compliant = assessment.controlResults.filter((r) => r.status === "compliant").length;
  const partial = assessment.controlResults.filter((r) => r.status === "partial").length;
  const nonCompliant = assessment.controlResults.filter((r) => r.status === "non_compliant").length;
  const notAssessed = assessment.controlResults.filter((r) => r.status === "not_assessed").length;

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Audit Report - ${assessment.organization.name}</title>
<style>
  @page { margin: 20mm; }
  body { font-family: system-ui, sans-serif; font-size: 10pt; color: #111; line-height: 1.5; }
  h1 { font-size: 18pt; margin-bottom: 0; }
  h2 { font-size: 14pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 24px; }
  .meta { color: #666; font-size: 9pt; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 4px 6px; border-bottom: 1px solid #eee; font-size: 9pt; }
  th { background: #f5f5f5; }
  .summary { display: flex; gap: 16px; margin: 16px 0; }
  .stat { flex: 1; text-align: center; padding: 12px; border-radius: 6px; color: #fff; font-weight: 600; }
  .stat-compliant { background: #16a34a; }
  .stat-partial { background: #d97706; }
  .stat-noncompliant { background: #dc2626; }
  .stat-na { background: #6b7280; }
  .stat span { display: block; font-size: 18pt; }
  .evidence { font-size: 8pt; color: #666; }
  @media print { .no-print { display: none; } }
</style></head>
<body>
  <h1>Audit Report</h1>
  <p class="meta">${assessment.organization.name} | ${assessment.name} | Generated ${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}</p>
  <div class="summary">
    <div class="stat stat-compliant"><span>${compliant}</span>Compliant</div>
    <div class="stat stat-partial"><span>${partial}</span>Partial</div>
    <div class="stat stat-noncompliant"><span>${nonCompliant}</span>Non-Compliant</div>
    <div class="stat stat-na"><span>${notAssessed}</span>Not Assessed</div>
  </div>
  <table>
    <thead><tr><th>Code</th><th>Control</th><th>Domain</th><th>Status</th><th>Evidence</th><th>Notes</th></tr></thead>
    <tbody>
      ${assessment.controlResults.map((r) => `
        <tr>
          <td style="font-family: monospace;">${r.control.code}</td>
          <td>${r.control.name}</td>
          <td>${r.control.domain.code}</td>
          <td>${r.status.replace("_", " ").toUpperCase()}</td>
          <td class="evidence">${r.evidence.length > 0 ? r.evidence.map(e => e.filename ?? e.value.slice(0, 40)).join(", ") : "—"}</td>
          <td class="evidence">${r.notes ? r.notes.slice(0, 60) : "—"}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>
  <p class="meta no-print" style="margin-top: 24px;">Report generated by ComplyFlow &mdash; Use browser Print (Ctrl+P) to save as PDF.</p>
</body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="audit-report-${assessment.id.slice(0, 8)}.html"`,
    },
  });
}
